# Site settings
title: DarkEdges
email: info@darkedges.com
description: "Identity and Access Management"
baseurl: ""
url: "https://blog.darkedges.com"
twitter_username: DarkEdges
github_username:  DarkEdges

google_analytics: UA-330453-2

highlighter: rouge

future: true

# Build settings
markdown: kramdown
permalink: pretty
excerpt_separator: "<!-- more -->"

paginate: 10

gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist

